name: Azure Functions Deploy

on:
  push:
    branches:
      - main  # Set the branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip deployment package
      run: zip -r tinyerpfunction.zip .

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: tinyerpfunction  # Replace with your Function App name
        package: './tinyerpfunction.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
